@startuml SedtrailComponentsDataManagement
!include ./c4/C4_Component.puml

' LAYOUT_LANDSCAPE()

title SedTRAILS: Component Diagram for Data Management Module
scale 1.5

Person(analyst, "Analyst", "Postprocesses and visualizes simulation outputs")

Container(pathwayVisualizer, "Pathway Visualizer", "Python", "An application to generate plots and animations of sand particle pathways.")
Container(cache, "Simulation Caching and State Tracker", "Python", "Tracks simulation state and recovers simulation outputs to allow restarts, and reusing simulation inputs and outputs")

Container(particleTracer, "Lagrangian Particle Tracer", "Python", "A desktop application that computes the position of sand particles (x,y,t) in a costal system")

Container(transportConverter, "Transport Converter", "Python", "An application that provides custom interfaces and methods for reading and converting 'transport flow-field data' to SedTRAILS compatible formats and physical units.")

SystemDb_Ext(fileSystem, "Local File System", "OS file system", $type="Windows, Linux, MacOS")

Container_Boundary(dataManager, "Data Management Module", "Python", "An application that manage data and files produced by the SedTRAILS Pacticle Tracer System"){
    ' Component(logReader, "Log Reader", "Python", "Read logs from a file produced by SedTRAILS Particle Tracer System")
    Component(logWriter, "Log Writer", "Python", "Writes log files produced by SedTRAILS Particle Tracer System")
    Component(fileReader, "NetCDF Reader", "Python", "Reads NetCDF files produced by the SedTRAILS Particle Tracer System")
    Component(fileWriter, "NetCDF Writer", "Python", "Writes NetCDF files produced by the SedTRAILS Particle Tracer System")
    Component(simulBuffer, "Simulation Data Buffer", "Python", "temporarly stores chunks of simulation data in memory, while they wait to be written.")
    Component(logBuffer, "Log Data Buffer", "Python", "temporarly stores chunks of logs in memory, while they wait to be written.")

    Component(memoryManager, "Memory Manager", "Python", "Manages memory allocation and deallocation for the data Buffers")

    Rel(simulBuffer, fileWriter, "provides chunks of simulation data to", "XArray")
    Rel(logBuffer, logWriter, "provides chunks logging data to", "Python object")

    Rel(memoryManager, simulBuffer, "allocates RAM for")
    Rel(memoryManager, logBuffer, "allocates RAM for")

}

Rel(fileReader, fileSystem, "Reads files from", "NETCDF")
Rel(fileWriter, fileSystem, "Writes files to", "NETCDF")

' Rel(logReader, fileSystem, "Reads log files from", "plain text")
Rel(logWriter, fileSystem, "Writes log files to", "plain text")
Rel(cache, logWriter, "Provides processing logs to", "Python object")

Rel(transportConverter, simulBuffer, "provides converted flow-field data to", "XArray")
Rel(particleTracer, simulBuffer, "provides output pathway data to", "XArray")
Rel(particleTracer, logBuffer, "provides processing time estimations to", "Python object")

Rel(cache, simulBuffer, "provides simulation state data to", "XArray")

Rel(fileReader, cache, "provides simulation chached data to", "XArray")

Rel(fileReader, pathwayVisualizer, "provides particle pathway data to", "NETCDF, XArray")
Rel(analyst, pathwayVisualizer, "Creates visualizations of particles pathways using", "Terminal")

SHOW_LEGEND()
@enduml

