@startuml SedtrailComponentsConverter
!include ./c4/C4_Component.puml

' LAYOUT_LANDSCAPE()

title SedTRAILS: Component Diagram for Transport Converter
scale 2

Container_Boundary(transportConverter, "Transport Converter"){ 
    Component(formatConverter, "Format Converter", "Python", "Converts flow-field data from various Eulerian flow modeling systems into a standard data structure")
    Component(physicsConverter, "Physics Converter", "Python", "Converts flow-field data from various Eulerian flow modeling systems into particle velocity using standard physical units")
        
    Rel(formatConverter, physicsConverter, "Provides flow-field data to", "standard data structure")
}

Container(particleTracer, "Lagrangian Particle Tracer", "Python", "A desktop application that computes the position of sand particles (x,y,t) in a costal system")

System_Ext(flowSystem, "Eulerian Flow Modeling System", "Simulates flows of water and wind", $type="Any")
SystemDb_Ext(fileSystem, "Local File System", "OS file system", $type="Windows, Linux, MacOS")

Rel(physicsConverter, particleTracer, "Provides transformed transport fields to", "memory/NETCDF")
Rel(physicsConverter, fileSystem, "Reads/writes pathway files to", "NETCDF")

Rel(flowSystem, formatConverter, "Provides flow-field data to ", "NETCDF")


SHOW_LEGEND()
@enduml

