@startuml SedtrailComponentsAnalysis
!include ./c4/C4_Component.puml

' LAYOUT_LANDSCAPE()

title SedTRAILS: Component Diagram for Simulation Analysis Application
scale 1.5


Container(sedtrailsInterface, "SedTRAILS Application Interface", "Python", "An application that enables users to access SedTRAILS functionality to run, visualize and analyze simulation")
SystemDb_Ext(fileSystem, "Local File System", "OS file system", $type="Windows, Linux, MacOS")

Container_Boundary(analystApp, "Simulation Analysis Application", "Python", "An application to post-process simulation outputs and conduct statistical and connectivity network analyses"){
    Component(fileReader, "NetCDF Reader", "Python", "Reads SedTRAILS simulation outputs")
    Component(fileWriter, "Results Writer", "Python", "Writes analysis results to files")
    Component(statistics, "Statistics Module", "Python", "Tools for statistical analysis")
    Component(connectivity, "Connectivity Network Module", "Python", "Tools for connectivity network analysis")
    Component(analysisManager, "Analysis Manager", "Python", "Coordinates analysis tasks and manages data flow between components")

    Rel(fileReader, statistics, "provides simulation data to", "Python object")
    Rel(fileReader, connectivity, "provides simulation data to", "Python object")   
    Rel(connectivity, fileWriter, "provides results to", "Python object")
    Rel(statistics, fileWriter, "provides results to", "Python object")
}

Rel(fileReader, fileSystem, "Reads simulation output files from", "NETCDF")
Rel(fileWriter, fileSystem , "Writes analysis results to", "NETCDF")
Rel(sedtrailsInterface, analysisManager, "access functionality to post-process and analyze simulation results", "Python")
Rel(analysisManager, statistics, "access functionality",)
Rel(analysisManager, connectivity, "access functionality",)

SHOW_LEGEND()
@enduml
