@startuml SedtrailComponentsTransportConverter
!include ./c4/C4_Component.puml

' LAYOUT_LANDSCAPE()

title SedTRAILS: Component Diagram for Transport Converter
scale 1.5

Person(modeler, "Modeler", "wants to track sand particles in a costal system")

Container(configInterface, "Simulation Configuration Interface", "Python", "An application that reads and interprets simulation configuration files")

Container_Boundary(transportConverter, "Transport Converter"){ 
    
    Component(formatConverter, "Format Converter Interface", "Python", "An interface to read flow-field data from an specific Eulerian flow modeling system and convert it to the SedTRAILS standard data structure")

    Component(physicsConverter, "Physics Converter", "Python", "Converts flow-field physical units using user-prefered conversion methods")
        
    Component(physicsLibrary, "Physics Convertion Library", "Python", "A library of methods for converting flow-field physical units")

    Rel(physicsConverter, physicsLibrary, "access methods for physics convertions", Python object")

    Rel(formatConverter, physicsConverter, "Provides flow-field data to", "SedTRAILS data structure, Python object")
    Rel(modeler, configInterface, "Defines simulation parameters and outputs for", "YAML")
    Rel(configInterface, physicsConverter, "provides configurations for physics convertions (e.g. method selection)", "Python object")
}

Container(sedtrailsLogger, "SedTRAILS  Logger", "Python", "An application that logs simulation states, outrputs, errors and computational performance metrics")

Container(particleTracer, "Lagrangian Particle Tracer", "Python", "A desktop application that computes the position of sand particles (x,y,t) in a costal system")

Container(dataManager, "Data Management Module", "Python", "An application that manage data and files produced by the SedTRAILS Pacticle Tracer System")

System_Ext(flowSystem, "Eulerian Flow Modeling System", "Simulates flows of water and wind and produces results a custom data structure", $type="Any")
SystemDb_Ext(fileSystem, "Local File System", "OS file system", $type="Windows, Linux, MacOS")

Rel(physicsConverter, dataManager, "Provides converted flow-field data to", "Python object")
Rel(sedtrailsLogger, physicsConverter, "access start/end times of routines in", "Python object")

Rel(physicsConverter, particleTracer, "Provides converted transport flow-field data to", "Python object")
Rel(dataManager, fileSystem, "Reads/writes converted flow-field data to", "NETCDF")

Rel( formatConverter, flowSystem, "reads flow-field input data from", "NETCDF")

SHOW_LEGEND()
@enduml

