@startuml SedtrailComponent
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Sedtrail Component Diagram
scale 2

' TODO: change name of the system to sedTRAILS
Person(modeler, "Modeler", "wants to track sand particles in a costal system")
Person(analyst, "Analyst", "wants postprocess and visualize simulation outputs")

Container_Boundary(sedtrailsApp, "SEDTrails Application"){ 
    Component(particleSeed, "Particle Seeding Tool", "Python", "?")
    Component(particleTracer, "Lagrangian Particle Traceer", "Python", "computes particle pathways (x,y,t) based on transport fields")
    Component(transportConverter, "Transport Converter", "Python", "converts...")
    Component(visualizer, "Pathway Visualizer", "Python", "produces aniamations of particle pathways")
    Component(connectivityBuilder, "Connectivity Network Builder", "Python", "computes connectiby nerworks of particles")
    Component(statisticalAnalyser, "Statistical Analysis ToolKit", "Python", "computes statistical analysis of particle pathways. (is this different than Analytical Tooling System?)")

    Component(dataInterface, "Pathway Interface ?", "Python", "A common interface to obtain particle pathways")

    Rel(particleSeed, particleTracer, "provides initial particle distribution to", "?")
    Rel(transportConverter, particleTracer, "provides transport field to ?", "memory, NETCDF file")
    Rel(particleTracer, visualizer, "provides particle pathways to", "memory, NETCDF file")
    Rel(particleTracer, connectivityBuilder, "provides particle pathways to", "memory, NETCDF file")
    Rel(particleTracer, statisticalAnalyser, "provides particle pathways to ", "memory, NETCDF file")
}



System_Ext(flowSystem, "Eulerian Flow Modeling System", "Simulates flows of water and wind", $type="Any")

' System_Ext(analyticalSystem, "Analytical Tooling System", "Provide statistical analysis tools to postproces simuation results", $type="Any")

Rel(modeler, particleSeed, "provides input parameters and select outputs to be saved to..?", "Configuration file")
Rel(analyst, particleTracer, "access simulation outputs from", "NETCDF")
Rel(modeler, flowSystem, "runs flow field computations in", "?")

Rel(flowSystem, transportConverter, "provides flow field data to ", "NETCDF")

' Rel(analyst, analyticalSystem, "post-process simuation outputs in ", "NETCDF")

SHOW_LEGEND()
@enduml

