@startuml SedtrailComponentsTransportConverter
!include ./c4/C4_Component.puml

title SedTRAILS: Component Diagram for Transport Converter
scale 1.5

Container(simOrchestrator, "Simulation Orchestrator", "Python", "Coordinates and manages the execution of SedTRAILS simulation tasks, including initialization, time-stepping, and termination procedures.")

Container_Boundary(transportConverter, "Transport Converter"){ 
    Component(formatConverter, "Format Converter", "Python", "An application that interprets flow-field data from a specific Eulerian flow modeling system and converts it to the SedTRAILS standard data structure")
    Component(physicsConverter, "Physics Converter", "Python", "Converts flow-field physical units using user-preferred conversion methods")
    Component(physicsLibrary, "Physics Conversion Library", "Python", "A library of 'tracer methods' for converting flow-field physical units")
    Component(flowDataRetriever, "Flow Field Data Retriever", "Python", "Retrieves flow-field data batches and manages data convertions in the transport converter, using a batch processing strategy")
    Component(flowDataBuffer, "Flow Field Data Buffer", "Python, Memory", "Stores flow-field data for fast access during particle tracing for a given time step")

    Rel(physicsConverter, physicsLibrary, "access methods for physics conversions", "Python")
    Rel(formatConverter, physicsConverter, "submits formatted flow-field data to", "SedTRAILS data structure, Python object")
    Rel(flowDataRetriever, flowDataBuffer, "loads flow-field data batch to", "Data array")
    Rel(simOrchestrator, flowDataRetriever, "provides configuration to retrieve flow-field data using", "Python")
    Rel(simOrchestrator, formatConverter, "provides configurations for format conversion", "Python")
    Rel(simOrchestrator, physicsConverter, "provides configurations for physics conversion", "Python")
    Rel(flowDataRetriever, formatConverter, "submits buffered flow-field data batch to", "Data array")
}

Container(sedtrailsLogger, "SedTRAILS  Logger", "Python", "An application that logs simulation states, outputs, errors and computational performance metrics")
Container(particleTracer, "Lagrangian Particle Tracer", "Python", "A desktop application that computes the position of sand particles (x,y,t) in a coastal system")
Container(dataManager, "Data Management Module", "Python", "An application that manage data and files produced by the SedTRAILS Particle Tracer System")

System_Ext(flowSystem, "Eulerian Flow Modeling System", "Simulates flows of water and wind and produces results a custom data structure", $type="Any")
SystemDb_Ext(fileSystem, "Local File System", "OS file system", $type="Windows, Linux, MacOS")

Rel(flowDataRetriever, dataManager, "Provides converted flow-field data to", "SedTRAILS data structure")
Rel(flowDataRetriever, sedtrailsLogger, "logs conversion states and performance metrics to", "Python")
Rel(flowDataRetriever, particleTracer, "Provides converted transport flow-field data to", "SedTRAILS data structure")
Rel(dataManager, fileSystem, "Reads/writes converted flow-field data to", "NETCDF")
Rel(flowDataRetriever, flowSystem, "reads flow-field input data from", "NETCDF")

SHOW_LEGEND()
@enduml

