@startuml SedtrailComponentsConverter
!include ./c4/C4_Component.puml

' LAYOUT_LANDSCAPE()

title SedTRAILS: Component Diagram for Simulation Configuration Interface
scale 1

Person(modeler, "Modeler", "wants to track sand particles in a costal system")
Container(particleTracer, "Lagrangian Particle Tracer", "Python", "A desktop application that computes the position of sand particles (x,y,t) in a costal system")
Container(transportConverter, "Transport Converter", "Python", "An application that provides custom interfaces and methods for reading and converting 'transport flow-field data' to SedTRAILS compatible formats and physical units.")

Container_Boundary(configInterface, "Simulation Configuration Interface", "Python", "An application that reads and interprets simulation configuration files"){
    Component(configReader, "Configuration Reader", "Python", "Reads simulation configuration files and provides configurations to other components")
    Component(configValidator, "Configuration Validator", "Python", "Validates simulation configuration files")
    Rel(configReader, configValidator, "provides file content to", "Python object")
}

Rel(modeler, configReader, "Defines simulation parameters and outputs for", "Plain text, Configuration file")
Rel(configReader, particleTracer, "provides cofigurations to", "Python object")
Rel(configReader, transportConverter, "provides cofigurations to", "Python object")

SHOW_LEGEND()
@enduml

