@startuml SedtrailComponent
' !include <C4/C4_Container>

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' LAYOUT_LANDSCAPE()

title sedTRAILS: Component Diagram for Lagrangian Particle Tracer
' scale 2

AddElementTag("review", $bgColor="lightred", $fontColor="red", $borderColor="red")

Person(modeler, "Modeler", "wants to track sand particles in a costal system")

Container(transportConverter, "Transport Converter", "Python", "An application that pre-process transport flow-field data to convert it to compatible formats and physical units.")

Container(cache, "Simulation Caching and State Tracker", "Python", "keeps track of simulation state and cache simulation outputs to allow restarts, and reusing simulation outputs")

Container_Boundary(sedtrailsTracer, " Lagrangian Particle Tracer"){ 
    Component(seedingTool, "Particle Seeding Tool", "Python", "computes initial particle positions and  particle's release times using various particle release strategies")
    Component(particleTracer, "Particle Tracer", "Python", "computes particle pathways based on particle positions and transport flow-field data")
    Component(pathwayWriter, "Particle Data Writer", "Python, NETCDF", "writes particle positions and properties to files")

    Component(particleStatusCheker, "Particle Status Checker", "Python", "checks whether particles are active, dead, alive, stuck, etc., during simulation", $tags="review")
    Component(particleBurialCheker, "Particle Burial Checker", "?",  "Check wether particles are trapped or free", $tags="review")
    Component(particleBurialCheker, "Particle Burial Checker", "?", "Check wether particles are trapped or free", $tags="review")
    Component(positionCalculator, "Particle Position Calculator", "?", "Calculates particle position at next time step", $tags="review")
    Component(propertyInterpolator, "Particle Property Interpolator", "?", "Interpolates particle properties at new positions from scalar fields", $tags="review")


    Rel(modeler, seedingTool, "defines seeding parameters for", "Configuration file")
    Rel(modeler, particleTracer, "defines simulation parameters for", "Configuration file")
    Rel(seedingTool, particleTracer, "provides particle positions and release times to ", "Python")
    Rel(particleTracer, pathwayWriter, "provides output pathways to", "Python")
    Rel(particleTracer, cache, "uses")
    Rel(seedingTool, cache, "uses")
    
}

Component_Ext(solver, "Runge-Kutta 4 Solver", "?", "Calculates ...")
SystemDb_Ext(fileSystem, "Local File System", "OS file system", $type="Windows, Linux, MacOS")

Rel(positionCalculator, solver, "uses")
Rel(pathwayWriter, fileSystem, "write pathway files to", "NETCDF")
Rel(transportConverter, particleTracer, "provides transformed transport flow-field data to", "Python")

SHOW_LEGEND()
@enduml

