@startuml SedtrailContainer
!include ./c4/C4_Container.puml

title sedTRAILS Container Diagram
scale 1.5
' LAYOUT_LANDSCAPE()


Person(modeler, "Modeler", "Tracks sand particles in a costal system")
Person(analyst, "Analyst", "Postprocesses and visualizes simulation outputs")

System_Boundary(sedtrailsSystem, "SedTRAILS Particle Tracking System"){ 
    Container(sedtrailsTracer, "Lagrangian Particle Tracer", "Python", "An application that computes the current and future position of sand particles (x,y,t) in a costal system")

    Container(configInterface, "Simulation Configuration Interface", "Python", "An application that reads and interprets simulation configuration files")

    Container(transportConverter, "Transport Converter", "Python", "An application that provides custom interfaces and methods for reading and converting 'transport flow-field data' to SedTRAILS compatible formats and physical units.")
    Container(pathwayVisualizer, "Pathway Visualizer", "Python", "An application to generate plots and animations of sand particle pathways.")
    Container(cache, "Simulation Caching and State Tracker", "Python", "Tracks simulation state and recovers simulation outputs to allow restarts, and reusing simulation inputs and outputs")
    Container(dataManager, "Data Management Module", "Python", "An application that manage data and files produced by the SedTRAILS Pacticle Tracer System")

    ' Container(connectivityNetworkSys, "Connectivity Network Application", "Python", "Tools for connectivity network analysis")

    ' Container(statisticsSys, "Statistical Analysis Application", "Python", "Tools for various statistical analysis")

    Container(analystApp, "Simulation Analysis Application", "Python", "An application to post-process simulation outputs and conduct statistical and connectivity network analyses")
 
    Rel(transportConverter, sedtrailsTracer, "Provides converted flow-field data to", "Python object")

    Rel(cache, sedtrailsTracer, "tracks simulation states and outputs, and provides cached flow-field data", "Python object")
    Rel(configInterface, transportConverter, "provides configuration for physics convertions to", "Python object")
    Rel(configInterface, sedtrailsTracer, "provides configuration for", "Python object")
    Rel(sedtrailsTracer, dataManager, "provides simulation outputs to", "Python object")

    Rel(transportConverter, dataManager, "provides converted flow-field data to", "Python object") 
    Rel(cache, dataManager, "provides simulation states, and retrieves cached data via", "Any") 

    Rel(dataManager, pathwayVisualizer, "provides pathway data to", "NETCDF, Python")
}
System_Ext(flowSystem, "Eulerian Flow Modeling System", "Simulates flows of water and wind", $type="Any")

SystemDb_Ext(fileSystem, "Local File System", "OS file system", $type="Windows, Linux, MacOS")

Rel(dataManager, fileSystem, "Read/Writes files to", "NETCDF, CSV, TXT, other")

Rel(modeler, configInterface, "Defines simulation parameters and outputs for", "Configuration file")

' Rel(dataManager, connectivityNetworkSys,  "Accesses simulation outputs using", "NETCDF")
' Rel(dataManager, statisticsSys,  "provides simulation outputs to", "NETCDF")

Rel(analyst, pathwayVisualizer, "Creates visualizations of sand pathways using", "Python")
Rel(analyst, analystApp, "Post-processes simulation outputs in", "Any")
Rel(analystApp, fileSystem, "Reads simulation outputs and writes analysis results", "Any")

' Rel(analyst, statisticsSys, "Post-processes simulation outputs in", "Any")

Rel(modeler, flowSystem, "Produces flow-field data using", "Any")
Rel(transportConverter, flowSystem, "Reads flow-field data from", "NETCDF")

SHOW_LEGEND()
@enduml