@startuml SedtrailContainer
!include ./c4/C4_Container.puml

title sedTRAILS Container Diagram
scale 1.5
' LAYOUT_LANDSCAPE()

Person(modeler, "Modeler", "Tracks particles in a coastal system")
Person(analyst, "Analyst", "Processes and visualizes simulation outputs")

System_Boundary(sedtrailsSystem, "SedTRAILS Particle Tracking System"){ 
    Container(sedtrailsTracer, "Lagrangian Particle Tracer", "Python", "A parallel processing application that computes the current and future position of sand particles (x,y,t) in a coastal system")
    Container(simOrchestrator, "Simulation Orchestrator", "Python", "Coordinates and manages the execution of SedTRAILS simulation tasks, including initialization, time-stepping, and termination procedures.")
    Container(simulationDashboard, "Simulation Dashboard", "Python, Qt", "A GUI to visualize simulation results in real-time")
    Container(sedtrailsInterface, "SedTRAILS Application Interface", "Python", "An application that enables users to access SedTRAILS functionality to run, visualize and analyze simulation")
    Container(sedtrailsLogger, "SedTRAILS  Logger", "Python", "An application that logs simulation states, outputs, errors and computational performance metrics")
    Container(transportConverter, "Transport Converter", "Python", "An application that provides custom interfaces and methods for reading and converting 'transport flow-field data' to SedTRAILS compatible formats and physical units.")
    Container(pathwayVisualizer, "Pathway Visualizer", "Python", "An application to generate plots and animations of  simulated particle pathways.")
    Container(cache, "Simulation Cache and Recovery", "Python", "Provides functionality to recover simulation interruptions, allow restarts, and reuse simulation inputs and outputs to avoid redundant computations.")
    Container(dataManager, "Data Management Module", "Python", "An application that manages data and files produced by the SedTRAILS Particle Tracer System")
    Container(analystApp, "Simulation Analysis Application", "Python", "An application to post-process simulation outputs and conduct statistical and connectivity network analyses")
    Rel(sedtrailsInterface, simOrchestrator, "provides configurations to execute simulations", "Python object")
    
    Rel(simOrchestrator, cache, "caches simulation configurations to", "Python object")
    Rel(sedtrailsInterface, analystApp, "access functionality to analyze simulation results", "Python")
    Rel(sedtrailsInterface, pathwayVisualizer, "access functionality to visualize simulation inputs and outputs", "Python")
    Rel(simOrchestrator, simulationDashboard, "provides input and simulated data to", "Python object")
    Rel(sedtrailsTracer, transportConverter,  "uses converted flow-field data from", "Python object")
    Rel(simOrchestrator, sedtrailsLogger,  "logs simulation states, steps, processing times and outputs to", "Python object")
    Rel(sedtrailsTracer, cache,  "caches particle positions using", "Python object")
    Rel(simOrchestrator, transportConverter, "provides configuration for format and physics conversions to", "Python object")
    Rel(simOrchestrator, sedtrailsTracer, "provides simulation configurations for", "Python object")
    Rel(sedtrailsTracer, dataManager, "provides particles' positions and  interpolated properties to", "Data array")
    Rel(transportConverter, cache, "caches converted transport flow-field data using", "Python object") 
    Rel(cache, dataManager, "stores and retrieves cached simulation states, flow-field data, and particle positions via", "Data array, Python object" ) 
    Rel(dataManager, pathwayVisualizer, "provides particle pathway data to", "NETCDF, Python")
}

System_Ext(flowSystem, "Eulerian Flow Modeling System", "Simulates and produces flow fields (water and wind) data", $type="Any")
SystemDb_Ext(fileSystem, "Local File System", "OS file system", $type="Windows, Linux, MacOS")

Rel(dataManager, fileSystem, "reads/writes simulation results and cache files to", "NETCDF, Pickle files")
Rel(modeler, sedtrailsInterface, "performs simulation, visualization and data analysis tasks using", "YAML, Configuration file, Python, Terminal")
Rel(cache, fileSystem, "reads simulation log files from", "Python object")
Rel(analyst, sedtrailsInterface, "post-process and analyze simulation outputs in", "Python, Terminal")
Rel(analystApp, fileSystem, "reads simulation outputs and writes analysis results", "Any")
Rel(sedtrailsLogger, fileSystem, "writes log files to", "Plain text")
Rel(modeler, flowSystem, "produces transport flow-field data using", "Any")
Rel(modeler, simulationDashboard, "monitors simulation results using", "GUI")
Rel(transportConverter, flowSystem, "reads flow-field data from", "Python")

SHOW_LEGEND()
@enduml
