@startuml SedtrailContainer
!include ./c4/C4_Container.puml

title SedTRAILS Container Diagram
scale 2

Person(modeler, "Modeler", "Tracks sand particles in a costal system")
Person(analyst, "Analyst", "Postprocesses and visualize simulation outputs")

System_Boundary(sedtrailsSystem, "SedTRAILS Particle Tracking System"){ 
    Container(sedtrailsTracer, "Lagrangian Particle Tracer", "Python", "An application that computes the position of sand particles (x,y,t) in a costal system")
    Container(transportConverter, "Transport Converter", "Python", "An application that converts processes transport flow-field data to compatible formats and physical units.")
    Container(pathwayVisualizer, "Pathway Visualizer", "Python", "An application to generate plots and animations of sand particle pathways.")
    Container(cache, "Simulation Caching and State Tracker", "Python", "Keeps track of simulation state and cache simulation outputs to allow restarts, and reusing simulation outputs")

    Container(connectivityNetworkSys, "Connectivity Network Application", "Python", "Tools for connectivity network analysis")
    Container(statisticsSys, "Statistical Analysis Application", "Python", "Tools for various statistical analysis")
    
    Rel(transportConverter, sedtrailsTracer, "Provides transformed transport data to")
    Rel(sedtrailsTracer, pathwayVisualizer, "Provides pathways to", "NETCDF")
    Rel(sedtrailsTracer, cache,  "uses")
    Rel(transportConverter, cache,  "uses")
}

System_Ext(flowSystem, "Eulerian Flow Modeling System", "Simulates flows of water and wind", $type="Any")


SystemDb_Ext(fileSystem, "Local File System", "OS file system", $type="Windows, Linux, MacOS")
Rel(sedtrailsTracer, fileSystem, "Writes transformed transport files to", "NETCDF")
Rel(transportConverter, fileSystem, "Write pathway files to", "NETCDF")

Rel(modeler, sedtrailsTracer, "Defines simulation parameters and outputs for", "Configuration file")
Rel(connectivityNetworkSys, sedtrailsTracer, "Accesses simulation outputs from", "NETCDF")
Rel(statisticsSys, sedtrailsTracer, "Accesses simulation outputs from", "NETCDF")
Rel(analyst, pathwayVisualizer, "Creates visualizations of sand pathways using", "Python")
Rel(analyst, connectivityNetworkSys, "Post-processes simulation outputs in", "Any")
Rel(analyst, statisticsSys, "Post-processe simulation outputs in", "Any")

Rel(modeler, flowSystem, "Produces flow-field data using", "Any")
Rel(flowSystem, transportConverter, "Provides flow-field data to ", "NETCDF")


SHOW_LEGEND()
@enduml