@startuml SedtrailContext
!include ./c4/C4_Context.puml

' !theme C4_sandstone from ./c4/themes
title SedTRAILS System Context Diagram
scale 2

Person(modeler, "Modeler", "Tracks particles in a coastal system")
Person(analyst, "Analyst", "Processes and visualizes simulation outputs")

System(sedtrails, "SedTRAILS Particle Tracking System", "Simulates the position of particles (x,y,z) in a coastal system over time", $type="Python application")

System_Ext(flowSystem, "Eulerian Flow Modeling System", "Simulates and produces flows fileds (water and wind) data", $type="Any")

SystemDb_Ext(fileSystem, "Local File System", "OS file system", $type="Windows, Linux, MacOS")

Rel(analyst, sedtrails, "processes simulation outputs in ", "CLI, Python")
Rel(sedtrails, fileSystem, "reads/writes result files to", "NETCDF, CSV, TXT")

Rel(modeler, sedtrails, "Defines simulation parameters and outputs for", "Configuration file")
Rel(modeler, flowSystem, "Produces flow-field data using" )

Rel(flowSystem, sedtrails, "Provides flow-field data to ", "NETCDF, Delft3D binaries")

SHOW_LEGEND()
@enduml
